apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-petclinic
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-petclinic
    spec:
      containers:
        - name: app
          image: spring-petclinic:latest
          imagePullPolicy: Never  # to pull from local registry
          ports:
            - containerPort: 8080
              name: http
