apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: spring-petclinic
  ports:
    - port: 8080
      targetPort: http
      nodePort: 31000
